set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()


Plugin 'gmarik/vundle'
Plugin 'Valloric/YouCompleteMe'
Plugin 'raimondi/delimitmate'
Plugin 'alvan/vim-closetag'
Plugin 'reedes/vim-pencil'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'junegunn/goyo.vim'
Plugin 'Yggdroot/indentLine'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'vim-syntastic/syntastic'
Bundle 'edkolev/tmuxline.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()            " required
filetype plugin indent on    " required


let g:UltiSnipsExpandTrigger='<c-b>' 
let g:UltiSnipsJumpForwardTrigger='<c-b>'
let g:UltiSnipsJumpBackwardTrigger='<c-k>'

let g:ycm_key_list_select_completion =["<tab>"]
let g:ycm_key_list_previous_completion = ["<s-tab>"]

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
hi Visual ctermfg=16 ctermbg=67

let g:tmuxline_powerline_separators = 0
let g:airline_theme='angr'
let g:airline#extensions#tabline#formatter = 'default'
let g:airline#extensions#tmuxline#enabled = 1
let airline#extensions#tmuxline#snapshot_file = "~/.tmux-status.conf"
 

syntax on
set number
set wildmenu
set showcmd
set hlsearch
set statusline+=%F
set laststatus=2
set tabstop=4
set tw=79
set backspace=2
set incsearch
